TARGET = opencv-stereo
SOURCES = opencv-stereo.cpp opencv-stereo-util.cpp barrymoore.cpp RecordingManager.cpp ../../externals/jpeg-utils/jpeg-utils.c ../../ui/hud/hud.cpp ../../utils/utils/RealtimeUtils.cpp

SUBPROJS = opencv-calibrate opencv-cam-calib-test


# include a standard makefile that uses these variables and builds everything
include ../../utils/make/flight.mk

