#!/bin/bash

sleep 15
/home/linaro/realtime/drivers/lcm_to_xbee_bridge2/lcm-to-xbee-bridge2 /dev/ttyUSB0 STATE_ESTIMATOR_POSE 150 process_status 0 process_status_cam 0 log_size 0 TIMESYNC 0 &
sleep 1
/home/linaro/realtime/drivers/process_control/process-control process_control stereo_control process_status /home/linaro/realtime/config/processControl.conf &
sleep 1
/home/linaro/realtime/ui/log-monitor/log-monitor log_size /home/linaro/ &
sleep 1
bot-lcm-tunnel -l udpm://239.255.76.67:7667?ttl=1 &
sleep 1
bot-procman-deputy -u udpm://239.255.76.67:7667?ttl=1 &

