#!/bin/bash

sleep 10
bot-procman-deputy -u udpm://239.255.76.67:7667?ttl=1 &
sleep 1
bot-lcm-tunnel &
/home/linaro/realtime/drivers/process_control/process-control process_control stereo_control process_status /home/linaro/realtime/config/processControl.conf &
