#!/bin/bash

# converts lcm logs in the standard log directory structure to .mat files

if [[ $1 == "" ]]
then
    echo "Usage: convertAllDogs [log directory]"
    exit 1
fi

CONVERT_DIR=$1

# convert logs in the gps folder

#for file in `ls $CONVERT_DIR/gps-logs/lcmlog-* |grep -v ".jlp"`
#do
    #./convertDeltawingSingle $file
#done

echo "------------------------"
echo "Converting local logs..."
echo "------------------------"
find $CONVERT_DIR/local-logs/ -name "lcmlog-*" |grep -v ".jlp" | xargs -n 1 -P 8 ./convertDeltawingSingle

echo "------------------------"
echo "Converting odroid-gps1 logs..."
echo "------------------------"

find $CONVERT_DIR/odroid-gps1/ -name "lcmlog-*" |grep -v ".jlp" | xargs -n 1 -P 8 ./convertDeltawingSingle

echo "------------------------"
echo "Converting odroid-gps2 logs..."
echo "------------------------"
find $CONVERT_DIR/odroid-gps2/ -name "lcmlog-*" |grep -v ".jlp" | xargs -n 1 -P 8 ./convertDeltawingSingle

echo "------------------------"
echo "Converting odroid-cam1 logs..."
echo "------------------------"

find $CONVERT_DIR/odroid-cam1/ -name "lcmlog-*" |grep -v ".jlp" | xargs -n 1 -P 8 ./convertDeltawingSingle

echo "------------------------"
echo "Converting odroid-cam2 logs..."
echo "------------------------"

find $CONVERT_DIR/odroid-cam2/ -name "lcmlog-*" |grep -v ".jlp" | xargs -n 1 -P 8 ./convertDeltawingSingle

