#!/bin/bash

# download videos

HOST=$2

# get the date out of the input string

THISDATE=`expr match $1 ".*\([0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]\)"`

#echo "Compressing videos for $THISDATE on $HOST..."

#ssh linaro@$HOST "ls /home/linaro/realtime/sensors/stereo/vids/video*$THISDATE* |wc -l"

#ssh linaro@$HOST "tar --checkpoint=1000 -czf videos-$HOST-$THISDATE.tar.gz /home/linaro/realtime/sensors/stereo/vids/video*$THISDATE*"

#echo "Downloading videos for $THISDATE from $HOST..."

#scp -r linaro@$HOST:/home/linaro/videos-$HOST-$THISDATE.tar.gz $1/onboard/
#scp -r linaro@$HOST:/home/linaro/realtime/sensors/stereo/vids/video*$THISDATE* $1/onboard


rsync -r --progress --no-inc-recursive linaro@$HOST:/home/linaro/realtime/sensors/stereo/vids/video*$THISDATE* $1/onboard



#echo "Decompressing videos..."

#tar -xzvf $1/onboard/videos-$HOST-$THISDATE.tar.gz

