#!/bin/bash

# download logs
echo "Please enter the hostname:"
echo -n "odroid-"
read HOST_END

HOST="odroid-$HOST_END"

# get the date out of the input string

THISDATE=`expr match $1 ".*\([0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]\)"`

#echo "Compressing logs for $THISDATE on $HOST..."

#ssh linaro@$HOST "tar -cvzf logs-$HOST-$THISDATE.tar.gz lcmlog-$THISDATE.*"

echo "Downloading logs for $THISDATE from $HOST..."

#scp linaro@$HOST:/home/linaro/logs-$HOST-$THISDATE.tar.gz $1

echo $HOST
rsync --progress --no-inc-recursive -z odroid@$HOST:lcmlog-$THISDATE.* $1
