#!/bin/bash

# download logs
echo "Please enter the hostname:"
echo -n "odroid-"
read HOST_END

REMOTE_DIR="$1"
LOCAL_DIR="$2"

OPTIONS=$3

if [[ $HOST_END == *"cam"* ]]
then
    # this is a multi-hop download, figure out the number in the download
    ODROID_NUMBER=${HOST_END: -1}

    echo "Detected multihop through odroid-gps$ODROID_NUMBER"
    echo -n "    odroid-"

    SSH_TRANSPORT="-e ssh -A odroid@odroid-gps$ODROID_NUMBER ssh odroid@odroid-$HOST_END"

else
    SSH_TRANSPORT="odroid@odroid-$HOST_END"
fi

mkdir -p $LOCAL_DIR/odroid-$HOST_END

echo "Downloading logs for from: $SSH_TRANSPORT..."


if [[ $HOST_END == *"cam"* ]]
then
    echo rsync --progress --no-inc-recursive --ignore-existing -a $OPTIONS "$SSH_TRANSPORT" :$REMOTE_DIR $LOCAL_DIR/odroid-$HOST_END
    rsync --progress --no-inc-recursive --ignore-existing -a $OPTIONS "$SSH_TRANSPORT" :$REMOTE_DIR $LOCAL_DIR/odroid-$HOST_END
else
    echo rsync --progress --no-inc-recursive --ignore-existing -a $OPTIONS "$SSH_TRANSPORT":$REMOTE_DIR $LOCAL_DIR/odroid-$HOST_END
    rsync --progress --no-inc-recursive --ignore-existing -a $OPTIONS "$SSH_TRANSPORT":$REMOTE_DIR $LOCAL_DIR/odroid-$HOST_END
fi

