#!/bin/bash

# automatically create directories for a new log

VIDEODIR=$HOME/video/rlg/4-delta-wing-era

LOGDIR=$HOME/rlg/logs

# check for a flag that the user might want their own date
while getopts d flag; do
    case $flag in
        d)
            echo "Enter the date in YYYY-MM-DD format:"
            read DATESTR
            ;;
    esac
done

if [ -z "$DATESTR" ]; then
    DATESTR=`date "+%Y-%m-%d"`
fi

# query the user for the name of the directory

echo "Please enter the name:"
echo -n "$DATESTR-"
read DIRNAME

echo "Creating directories..."
echo "$VIDEODIR/$DATESTR-$DIRNAME"
mkdir $VIDEODIR/$DATESTR-$DIRNAME

echo "$LOGDIR/$DATESTR-$DIRNAME/onboard"
mkdir  -p $LOGDIR/$DATESTR-$DIRNAME/onboard

echo "$LOGDIR/$DATESTR-$DIRNAME/mat"
mkdir -p $LOGDIR/$DATESTR-$DIRNAME/mat

echo "Creating symlinks..."
echo "$VIDEODIR/$DATESTR-$DIRNAME -> $LOGDIR/$DATESTR-$DIRNAME/ground-vids"
ln -s $VIDEODIR/$DATESTR-$DIRNAME $LOGDIR/$DATESTR-$DIRNAME/ground-vids

echo "$LOGDIR/$DATESTR-$DIRNAME/onboard -> $VIDEODIR/$DATESTR-$DIRNAME/onboard"
ln -s $LOGDIR/$DATESTR-$DIRNAME/onboard $VIDEODIR/$DATESTR-$DIRNAME/onboard


# download logs
while true; do
    read -p "Do you want to download logs now?" yn
    case $yn in
        [Yy]* ) ./downloadLogs $LOGDIR/$DATESTR-$DIRNAME u2gps;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done

while true; do
    read -p "Do you want to download videos now?" yn
    case $yn in
        [Yy]* ) ./downloadVideos $LOGDIR/$DATESTR-$DIRNAME u2cam;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done
