#!/bin/bash

echo "---------------------------"
echo "       Running make        "
echo "---------------------------"


make

# create a symlink for other scripts
cd lib
ln -s libtypes.a libplanerlg.a
cd ..

echo "----------------------------"
echo "Patching mavlink_message_t.h"
echo "----------------------------"

echo "patch mavlink_message_t.h < mavlink_message.patch"
patch mavlink_message_t.h < mavlink_message.patch



export CLASSPATH="`pkg-config --variable=classpath lcm-java`:."

echo "---------------------------"
echo "    Building LCM types     "
echo "---------------------------"
for FILE in `ls types/*.lcm`
do
    lcm-gen -j $FILE
    lcm-gen -p $FILE
 
    # replace "types" in path with "lcmtypes" and ".lcm" with ".java"
    FILE2=${FILE/types/lcmtypes}
    
    # % says "search from back"
    echo "javac ${FILE2/%lcm/java}"
    javac ${FILE2/%lcm/java}

    #lcm-gen -j types/lcmt_glider_vicon.lcm
    #lcm-gen -p types/lcmt_glider_vicon.lcm

    #javac lcmtypes/lcmt_glider_vicon.java
    
done

jar cf LCMtypes.jar lcmtypes/*.class

