#!/bin/bash

# this script exists to test different serial port possibilities for ACM[0-1]

/home/linaro/mav/mavconn/build/bin/mavconn-bridge-serial -p /dev/ttyACM0 --pc2serial || /home/linaro/mav/mavconn/build/bin/mavconn-bridge-serial -p /dev/ttyACM1 --pc2serial || /home/linaro/mav/mavconn/build/bin/mavconn-bridge-serial -p /dev/ttyACM2 --pc2serial
