TARGET = tvlqr-controller

SOURCES = tvlqr-controller.cpp tvlqr-controller-main.cpp TvlqrControl.cpp ../TrajectoryLibrary/TrajectoryLibrary.cpp ../TrajectoryLibrary/Trajectory.cpp ../../externals/csvparser/csvparser.c ../../utils/utils/RealtimeUtils.cpp ../../utils/ServoConverter/ServoConverter.cpp ../../estimators/StereoOctomap/StereoOctomap.cpp


SUBPROJS = test

include ../../utils/make/flight.mk
