TARGET = hud-main
SOURCES = hud-main.cpp ../../sensors/stereo/opencv-stereo-util.cpp ../../externals/jpeg-utils/jpeg-utils.c hud.cpp ../../estimators/StereoOctomap/StereoOctomap.cpp ../../sensors/stereo/RecordingManager.cpp


include ../../utils/make/flight.mk
