#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage: sendGitBundle <plane_number>"
    exit 1
fi

cd $HOME/realtime



# upload to gps computer
echo "Sending to odroid-gps$1..."
scripts/sendGitBundleSingle odroid-gps$1

# upload to cam computer
echo "Sending to cam computer..."
ssh odroid@odroid-gps$1 "/home/odroid/realtime/scripts/sendGitBundleSingle  odroid-cam$1"
