#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage: sendGitBundleSingle <hostname>"
    exit 1
fi

cd $HOME/realtime

git bundle create commits.bundle HEAD~15..HEAD

rsync --progress commits.bundle odroid@$1:/home/odroid/

ssh odroid@$1 "/home/odroid/realtime/scripts/unpackGitBundle /home/odroid/commits.bundle"

rm commits.bundle
