#!/bin/bash

export CLASSPATH=$CLASSPATH:/home/abarry/MIT/RLG/robotlib3/robots/Plane/realtime/LCM/LCMtypes.jar:/home/abarry/MIT/RLG/Fixie/build/share/java/lcmtypes_mav-lcmtypes.jar:/home/abarry/MIT/RLG/Fixie/build/share/java/lcmtypes_mav_estimator.jar 

lcm-spy
