TARGET = mono-playback

SOURCES = mono-playback.cpp ../../utils/utils/RealtimeUtils.cpp ../../sensors/stereo/opencv-stereo-util.cpp ../../externals/jpeg-utils/jpeg-utils.c

include ../../utils/make/flight.mk
